"""
novafin-capstone/src/novafin/data/profile.py

Profiling tables for exploratory analysis.

Every table the EDA notebook displays - and every table that later appears in
the D7 guide or the D8 deck - is produced by a function here, not by ad-hoc
code in a cell. Three reasons:

1. **Reproducibility.** A table in the report can be regenerated by calling one
   function, so it cannot silently drift from the data.
2. **Consistency.** All eight modules get the same column profile, the same
   decile-lift table and the same imbalance summary, which makes them
   comparable.
3. **Testability.** A function can be unit-tested; a notebook cell cannot.

Deliberately NOT using ``pandas-profiling`` / ``ydata-profiling``: it produces
a 40 MB HTML artefact that nobody reads, it is slow on the 120,000-row order
book, and its output cannot be dropped into a Word document or a slide. Eight
small, purpose-built tables beat one large generic one.
"""

from __future__ import annotations

import logging
from typing import Any, Sequence

import numpy as np
import pandas as pd

__all__ = [
    "column_profile",
    "dataset_overview",
    "class_balance",
    "decile_lift",
    "group_rate",
    "temporal_rate",
    "numeric_summary",
]

LOGGER = logging.getLogger(__name__)


def column_profile(frame: pd.DataFrame, *, max_top_values: int = 5) -> pd.DataFrame:
    """Per-column dtype, missingness, cardinality and range.

    This is the table that appears as "Data Audit" in the D7 guide, one block
    per dataset.

    Args:
        frame: Any dataframe.
        max_top_values: How many modal values to list for categorical columns.

    Returns:
        One row per column, with ``column, dtype, missing, missing_pct,
        n_unique, unique_pct, min, max, mean, std, top_values``.
    """
    rows: list[dict[str, Any]] = []
    n = len(frame)

    for column in frame.columns:
        series = frame[column]
        row: dict[str, Any] = {
            "column": column,
            "dtype": str(series.dtype),
            "missing": int(series.isna().sum()),
            "missing_pct": round(float(series.isna().mean() * 100), 3),
            "n_unique": int(series.nunique(dropna=True)),
            "unique_pct": round(float(series.nunique(dropna=True) / n * 100), 2) if n else 0.0,
            "min": None,
            "max": None,
            "mean": None,
            "std": None,
            "top_values": "",
        }

        if pd.api.types.is_numeric_dtype(series):
            numeric = series.astype("float64")
            row["min"] = float(numeric.min())
            row["max"] = float(numeric.max())
            row["mean"] = float(numeric.mean())
            row["std"] = float(numeric.std())
            if row["n_unique"] <= 12:
                counts = series.value_counts().head(max_top_values)
                row["top_values"] = ", ".join(f"{k}={v}" for k, v in counts.items())
        elif pd.api.types.is_datetime64_any_dtype(series):
            row["min"] = series.min()
            row["max"] = series.max()
        else:
            counts = series.value_counts().head(max_top_values)
            row["top_values"] = ", ".join(f"{k} ({v})" for k, v in counts.items())

        rows.append(row)

    return pd.DataFrame(rows)


def dataset_overview(results: dict[str, Any]) -> pd.DataFrame:
    """One-row-per-dataset inventory from a dict of ``LoadResult`` objects.

    Produces the "Dataset inventory" table used in the guide and on the Data
    slide of the deck.
    """
    rows = []
    for key, result in results.items():
        summary = result.summary()
        rows.append(
            {
                "dataset": key,
                "rows": summary["rows"],
                "cols": summary["cols"],
                "memory_mb": summary["memory_mb"],
                "sha256_16": summary["sha256_16"],
                "schema_ok": summary["schema_ok"],
            }
        )
    return pd.DataFrame(rows).sort_values("dataset").reset_index(drop=True)


def class_balance(frame: pd.DataFrame, target: str) -> pd.DataFrame:
    """Counts and proportions per class, plus the imbalance ratio.

    The imbalance ratio (majority / minority) is the number that decides
    whether PR-AUC is mandatory: at 2.28% fraud the ratio is ~43:1 and ROC-AUC
    becomes flattering, while at 19.94% default the ratio is ~4:1 and ROC-AUC
    is still informative.
    """
    counts = frame[target].value_counts(dropna=False)
    proportions = frame[target].value_counts(normalize=True, dropna=False)
    out = pd.DataFrame({"count": counts, "proportion": proportions.round(5)})
    out.index.name = target
    out = out.reset_index()
    if len(counts) >= 2:
        out["imbalance_ratio"] = round(float(counts.max() / counts.min()), 2)
    return out


def decile_lift(
    frame: pd.DataFrame,
    feature: str,
    target: str,
    *,
    n_bins: int = 10,
) -> pd.DataFrame:
    """Event rate of a binary target across quantile bins of a feature.

    This is the single most persuasive EDA table for an imbalanced problem: it
    shows whether a feature separates the classes *monotonically*, which a
    correlation coefficient alone cannot. It is what established that
    ``Amount`` moves the fraud rate from 0.60% to 12.67% across its deciles.

    Args:
        frame: Data.
        feature: Numeric feature to bin.
        target: Binary target column.
        n_bins: Number of quantile bins.

    Returns:
        ``bin, n, n_events, event_rate, lift`` where lift is the bin's event
        rate divided by the overall event rate.
    """
    working = frame[[feature, target]].dropna()
    if working.empty:
        return pd.DataFrame(columns=["bin", "n", "n_events", "event_rate", "lift"])

    bins = pd.qcut(working[feature], n_bins, duplicates="drop")
    grouped = working.groupby(bins, observed=True)[target]
    base_rate = float(working[target].mean())

    out = pd.DataFrame(
        {
            "n": grouped.size(),
            "n_events": grouped.sum(),
            "event_rate": grouped.mean().round(5),
        }
    ).reset_index()
    out = out.rename(columns={out.columns[0]: "bin"})
    out["bin"] = out["bin"].astype(str)
    out["lift"] = (out["event_rate"] / base_rate).round(3) if base_rate else np.nan
    return out


def group_rate(frame: pd.DataFrame, group: str, target: str) -> pd.DataFrame:
    """Event rate of a binary target per category, with counts.

    Counts are reported alongside the rate on purpose: a 100% event rate over
    three rows is noise, and a table that hides ``n`` invites that mistake.
    """
    grouped = frame.groupby(group, observed=True)[target]
    out = pd.DataFrame(
        {"n": grouped.size(), "n_events": grouped.sum(), "event_rate": grouped.mean().round(5)}
    ).reset_index()
    return out.sort_values("event_rate", ascending=False).reset_index(drop=True)


def temporal_rate(
    frame: pd.DataFrame, time_column: str, target: str, *, freq: str = "ME"
) -> pd.DataFrame:
    """Event rate resampled over time - the drift check.

    A fraud or default rate that trends over time invalidates a random split
    and changes how the holdout must be chosen. For this data the fraud rate is
    stationary month to month, which is itself worth stating in the report.
    """
    working = frame[[time_column, target]].dropna().set_index(time_column).sort_index()
    resampled = working[target].resample(freq)
    out = pd.DataFrame(
        {"n": resampled.size(), "n_events": resampled.sum(), "event_rate": resampled.mean().round(5)}
    ).reset_index()
    return out


def numeric_summary(frame: pd.DataFrame, columns: Sequence[str] | None = None) -> pd.DataFrame:
    """Descriptive statistics with the percentiles that matter for finance.

    Adds the 1st and 99th percentiles to the usual quartiles, because tail
    behaviour drives loss-given-default, VaR and fraud thresholds - and a
    summary that stops at the 75th percentile hides exactly the rows that cost
    money.
    """
    numeric = frame[list(columns)] if columns else frame.select_dtypes(include=[np.number])
    described = numeric.describe(percentiles=[0.01, 0.25, 0.5, 0.75, 0.99]).T
    described["skew"] = numeric.skew()
    described["kurtosis"] = numeric.kurtosis()
    return described.round(4)
